[versions]
it-unimi-dsi-fastutil = "8.5.18"
org-slf4j-slf4j-api = "2.0.17"
org-yaml-snakeyaml = "2.5"

[libraries]
it-unimi-dsi-fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "it-unimi-dsi-fastutil" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j-slf4j-api" }
org-yaml-snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "org-yaml-snakeyaml" }
